# !/usr/bin/python
# -*- coding: utf-8 -*-

from gensim.models import KeyedVectors

""" Word vector explorer =========================================            

                                                     asahala 2021 

This script provides basic tools for making queries from word
vectors. 

"""

def read_vectors(filename):
    return KeyedVectors.load_word2vec_format(filename)


def read_dict(filename):
    """ Parse dictionary file for freqs + translations. This file is
    automatically generated by ´extract_corpus.py´ """
    with open(filename, 'r', encoding='utf-8') as data:
        return {l:{'freq':int(f), 'translation':t} for l,f,t in
                (line.split('\t') for line in data.read().splitlines())}


def nearest_neighbors(word, num=10, min_freq=2):
    """ Find nearest neighbors (similarity) and pretty print.
    Negative cosine similarities will be ignored. 

    :param word            query word
    :param num             number of nearest neighbors
    :param min_freq        ignore neihgbors if rarer than this

    :type word             str
    :type num              int
    :type min_freq         int """

    if word not in vectors.vocab.keys():
        similar = []
        for key in vectors.vocab.keys():
            if key.startswith(word):
                similar.append(key)
        if similar:
            for s in similar:
                nearest_neighbors(s, num, min_freq)
        else:
            print('> No vector for %s' % word)
    else:
        print('-'*64)
        print(word + ' ' + dictionary[word]['translation'])
        print('-'*64)
        for lemma, cos_sim in vectors.most_similar(word, topn=10000):
            if cos_sim < 0:
                break
            if min_freq <= dictionary[lemma]['freq'] and num:
                num -= 1
                print('{:<8f} {:<20s} {:<6d} {:<40s}'.format(
                    round(cos_sim, 6),
                    lemma,
                    dictionary[lemma]['freq'],
                    dictionary[lemma]['translation']))

vectors = read_vectors('akk.vec')
dictionary = read_dict('akk_corpus.dict')
nearest_neighbors('nêru', num=15, min_freq=2)
